# Generated by Django 4.2.7 on 2024-05-16 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_id', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'texts',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_id', models.FileField(upload_to='voices/')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voices', to='tgbot.text')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voices', to='tgbot.user')),
            ],
            options={
                'db_table': 'voices',
            },
        ),
        migrations.CreateModel(
            name='VoiceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='tgbot.user')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='tgbot.voice')),
            ],
            options={
                'db_table': 'voice_checks',
            },
        ),
        migrations.AddConstraint(
            model_name='voicecheck',
            constraint=models.UniqueConstraint(fields=('user', 'voice'), name='unique_user_voice'),
        ),
    ]
