# Generated by Django 4.2.7 on 2024-05-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_text_voice_voicecheck_voicecheck_unique_user_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicePassed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'voice_passed',
            },
        ),
        migrations.RemoveConstraint(
            model_name='voicecheck',
            name='unique_user_voice',
        ),
        migrations.AddConstraint(
            model_name='voicecheck',
            constraint=models.UniqueConstraint(fields=('user', 'voice'), name='unique_user_check_voice'),
        ),
        migrations.AddField(
            model_name='voicepassed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passed', to='tgbot.user'),
        ),
        migrations.AddField(
            model_name='voicepassed',
            name='voice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed', to='tgbot.voice'),
        ),
        migrations.AddConstraint(
            model_name='voicepassed',
            constraint=models.UniqueConstraint(fields=('user', 'voice'), name='unique_user_passed_voice'),
        ),
    ]
