# Generated by Django 4.2.7 on 2024-05-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_voicepassed_remove_voicecheck_unique_user_voice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='voice_id',
            new_name='voice',
        ),
    ]
