# Generated by Django 4.2.7 on 2024-05-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_rename_voice_id_voice_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPassed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed', to='tgbot.text')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passed', to='tgbot.user')),
            ],
            options={
                'db_table': 'text_passed',
            },
        ),
        migrations.DeleteModel(
            name='VoicePassed',
        ),
        migrations.AddConstraint(
            model_name='textpassed',
            constraint=models.UniqueConstraint(fields=('user', 'text'), name='unique_user_passed_text'),
        ),
    ]
