# Generated by Django 4.2.7 on 2024-05-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_textpassed_delete_voicepassed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='voice_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
